### ISSUE TITLE
[Bug] 安装报错  @mui/material 找不到

### ISSUE THREAD

**Issue by sheng-di** [ant-design/pro-editor#148]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

报错：
```
error - ./node_modules/_@textea_json-viewer@3.3.0@@textea/json-viewer/dist/index.mjs:3:0-98
Module not found: Error: Can't resolve '@mui/material' in '/path/to/project/node_modules/_@textea_json-viewer@3.3.0@@textea/json-viewer/dist'
error - Error: ERROR in ./node_modules/_@textea_json-viewer@3.3.0@@textea/json-viewer/dist/index.mjs 3:0-98
Module not found: Error: Can't resolve '@mui/material' in '/path/to/project/node_modules/_@textea_json-viewer@3.3.0@@textea/json-viewer/dist'
 @ ./node_modules/_@ant-design_pro-editor@0.38.1@@ant-design/pro-editor/es/DataPreviewer/index.js 5:0-49 135:40-50
 @ ./node_modules/_@ant-design_pro-editor@0.38.1@@ant-design/pro-editor/es/index.js 11:0-32 11:0-32
 @ ./node_modules/.cache/mfsu/mf-va_@ant-design_pro-editor.js 1:0-114 1:0-114
 @ container entry ./@ant-design/pro-editor[0]

MFSU compiled with 1 error
    at /path/to/project/node_modules/_@umijs_preset-umi@4.1.0@@umijs/preset-umi/dist/commands/dev/depBuildWorker/depBuilder.js:64:20
    at finalCallback (/path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:62945:32)
    at /path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:63009:17
    at /path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:77363:3
    at Hook.eval [as callAsync] (eval at create (/path/to/project/node_modules/_@umijs_bundler-utils@4.1.0@@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/path/to/project/node_modules/_@umijs_bundler-utils@4.1.0@@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
    at Cache.storeBuildDependencies (/path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:52350:37)
    at /path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:63005:19
    at Hook.eval [as callAsync] (eval at create (/path/to/project/node_modules/_@umijs_bundler-utils@4.1.0@@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:47:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/path/to/project/node_modules/_@umijs_bundler-utils@4.1.0@@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
    at /path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:63002:23
    at Compiler.emitRecords (/path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:63423:5)
    at /path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:62994:11
    at /path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:63389:14
    at Hook.eval [as callAsync] (eval at create (/path/to/project/node_modules/_@umijs_bundler-utils@4.1.0@@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:10:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/path/to/project/node_modules/_@umijs_bundler-utils@4.1.0@@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
    at /path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:63386:27
    at /path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:39750:7
    at done (/path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:40454:9)
    at Hook.eval [as callAsync] (eval at create (/path/to/project/node_modules/_@umijs_bundler-utils@4.1.0@@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:6:1)
    at /path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:63240:33
    at /path/to/project/node_modules/_@umijs_bundler-webpack@4.1.0@@umijs/bundler-webpack/compiled/webpack/index.js:35193:16
    at /path/to/project/node_modules/_@umijs_utils@4.1.0@@umijs/utils/compiled/fs-extra/index.js:1:23246
    at FSReqCallback.oncomplete (node:fs:192:23)
```

### 🚦 期望结果 | Expected Behavior

正常安装。

### 📷 复现步骤 | Recurrence Steps

```
rm -rf node_modules && npm i && npm run dev
```

**Comment by ONLY-yours** [comment]
抱歉，已经回滚修复了 @mui/material 太大了，我这边要开一个专项到时候底层去掉
